using System;

namespace CityAPI.Controllers
{
    public class Store
    {

        public static string[] cityArray = { "Adana", "Adıyaman", "Afyon", "Ağrı", "Amasya", "Ankara", "Antalya", "Artvin", "Aydın", "Balıkesir", "Bilecik", "Bingöl",
            "Bitlis", "Bolu", "Burdur", "Bursa", "Çanakkale", "Çankırı", "Çorum", "Denizli", "Diyarbakır", "Edirne", "Elazığ", "Erzincan", "Erzurum", "Eskişehir",
            "Gaziantep", "Giresun", "Gümüşhane", "Hakkari", "Hatay", "Isparta", "İçel (Mersin)", "İstanbul", "İzmir", "Kars", "Kastamonu", "Kayseri", "Kırklareli",
            "Kırşehir", "Kocaeli", "Konya", "Kütahya", "Malatya", "Manisa", "Kahramanmaraş", "Mardin", "Muğla", "Muş", "Nevşehir", "Niğde", "Ordu", "Rize", "Sakarya", 
            "Samsun", "Siirt", "Sinop", "Sivas", "Tekirdağ", "Tokat", "Trabzon", "Tunceli", "Şanlıurfa", "Uşak", "Van", "Yozgat", "Zonguldak", "Aksaray", "Bayburt", "Karaman",
            "Kırıkkale", "Batman", "Şırnak", "Bartın", "Ardahan", "Iğdır", "Yalova", "Karabük", "Kilis", "Osmaniye", "Düzce" };

        public static District[] districtArray = new District[81];

        static public void districtFill()
        {
            districtArray[0] = new District { cityCode = 1, cityName = "Adana", districtName = new string[] { "Aladağ", "Ceyhan", "Çukurova", "Feke", "İmamoğlu", "Karaisalı", "Karataş", "Kozan", "Pozantı", "Saimbeyli", "Sarıçam", "Seyhan", "Tufanbeyli", "Yumurtalık", "Yüreğir" } };
            districtArray[1] = new District { cityCode = 2, cityName = "Adıyaman", districtName = new string[] { "Besni", "Çelikhan", "Gerger", "Gölbaşı", "Kâhta", "Samsat", "Sincik", "Tut" } };
            districtArray[2] = new District { cityCode = 3, cityName = "Afyonkarahisar", districtName = new string[] { "Başmakçı", "Bayat", "Bolvadin", "Çay", "Çobanlar", "Dazkırı", "Dinar", "Emirdağ", "Evciler", "Hocalar", "İhsaniye", "İscehisar", "Kızılören", "Sandıklı", "Sinanpaşa", "Sultandağı", "Şuhut" } };
            districtArray[3] = new District { cityCode = 4, cityName = "Ağrı", districtName = new string[] { "Diyadin", "Doğubayazıt", "Eleşkirt", "Hamur", "Patnos", "Taşlıçay", "Tutak"} };
            districtArray[4] = new District { cityCode = 5, cityName = "Amasya", districtName = new string[] { "Göynücek", "Gümüşhacıköy", "Hamamözü", "Merzifon", "Suluova", "Taşova" } };
            districtArray[5] = new District { cityCode = 6, cityName = "Ankara", districtName = new string[] { "Akyurt", "Altındağ", "Ayaş", "Balâ", "Beypazarı", "Çamlıdere", "Çankaya", "Çubuk", "Elmadağ", "Etimesgut", "Evren", "Gölbaşı", "Güdül", "Haymana", "Kalecik", "Kahramankazan", "Keçiören", "Kızılcahamam", "Mamak", "Nallıhan", "Polatlı", "Pursaklar", "Sincan", "Şereflikoçhisar", "Yenimahalle" } };
            districtArray[6] = new District { cityCode = 7, cityName = "Antalya", districtName = new string[] { "Akseki", "Aksu", "Alanya", "Döşemealtı", "Elmalı", "Finike", "Gazipaşa", "Gündoğmuş", "İbradı", "Demre", "Kaş", "Kemer", "Kepez", "Konyaaltı", "Korkuteli", "Kumluca", "Manavgat", "Muratpaşa", "Serik" } };
            districtArray[7] = new District { cityCode = 8, cityName = "Artvin", districtName = new string[] { "Arhavi", "Artvin", "Borçka", "Hopa", "Murgul", "Şavşat", "Yusufeli" } };
            districtArray[8] = new District { cityCode = 9, cityName = "Aydın", districtName = new string[] { "Bozdoğan", "Buharkent", "Çine", "Didim", "Efeler", "Germencik", "İncirliova", "Karacasu", "Karpuzlu", "Koçarlı", "Köşk", "Kuşadası", "Kuyucak", "Nazilli", "Söke", "Sultanhisar", "Yenipazar" } };
            districtArray[9] = new District { cityCode = 10, cityName = "Balıkesir", districtName = new string[] { "Altıeylül", "Ayvalık", "Balya", "Bandırma", "Bigadiç", "Burhaniye", "Dursunbey", "Edremit", "Erdek", "Gömeç", "Gönen", "Havran", "İvrindi", "Karesi", "Kepsut", "Manyas", "Marmara", "Savaştepe", "Sındırgı", "Susurluk" } };
            districtArray[10] = new District { cityCode = 11, cityName = "Bilecik", districtName = new string[] { "Bilecik", "Bozüyük", "Gölpazarı", "İnhisar", "Osmaneli", "Pazaryeri", "Söğüt", "Yenipazar" } };
            districtArray[11] = new District { cityCode = 12, cityName = "Bingöl", districtName = new string[] { "Adaklı", "Bingöl", "Genç", "Karlıova", "Kiğı", "Solhan", "Yayladere", "Yedisu" } };
            districtArray[12] = new District { cityCode = 13, cityName = "Bitlis", districtName = new string[] { "Adilcevaz", "Ahlat", "Güroymak", "Hizan", "Mutki", "Tatvan" } };
            districtArray[13] = new District { cityCode = 14, cityName = "Bolu", districtName = new string[] { "Dörtdivan", "Gerede", "Göynük", "Kıbrıscık", "Mengen", "Mudurnu", "Seben", "Yeniçağa" } };
            districtArray[14] = new District { cityCode = 15, cityName = "Burdur", districtName = new string[] { "Ağlasun", "Altınyayla", "Bucak", "Burdur", "Çavdır", "Çeltikçi", "Gölhisar", "Karamanlı", "Kemer", "Tefenni", "Yeşilova" } };
            districtArray[15] = new District { cityCode = 16, cityName = "Bursa", districtName = new string[] { "Büyükorhan", "Gemlik", "Gürsu", "Harmancık", "İnegöl", "İznik", "Karacabey", "Keles", "Kestel", "Mudanya", "Mustafakemalpaşa", "Nilüfer", "Orhaneli", "Orhangazi", "Osmangazi", "Yenişehir", "Yıldırım" } };
            districtArray[16] = new District { cityCode = 17, cityName = "Çanakkale", districtName = new string[] { "Ayvacık", "Bayramiç", "Biga", "Bozcaada", "Çan", "Çanakkale", "Eceabat", "Ezine", "Gelibolu", "Gökçeada", "Lapseki", "Yenice" } };
            districtArray[17] = new District { cityCode = 18, cityName = "Çankırı", districtName = new string[] { "Atkaracalar", "Bayramören", "Çerkeş", "Eldivan", "Ilgaz", "Kızılırmak", "Korgun", "Kurşunlu", "Orta", "Şabanözü", "Yapraklı" } };
            districtArray[18] = new District { cityCode = 19, cityName = "Çorum", districtName = new string[] { "Alaca", "Bayat", "Boğazkale", "Dodurga", "İskilip", "Kargı", "Laçin", "Mecitözü", "Oğuzlar", "Ortaköy", "Osmancık", "Sungurlu", "Uğurludağ" } };
            districtArray[19] = new District { cityCode = 20, cityName = "Denizli", districtName = new string[] { "Acıpayam", "Babadağ", "Baklan", "Bekilli", "Beyağaç", "Bozkurt", "Buldan", "Çal", "Çameli", "Çardak", "Çivril", "Güney", "Honaz", "Kale", "Merkezefendi", "Pamukkale", "Sarayköy", "Serinhisar", "Tavas" } };
            districtArray[20] = new District { cityCode = 21, cityName = "Diyarbakır", districtName = new string[] { "Bağlar", "Bismil", "Çermik", "Çınar", "Çüngüş", "Dicle", "Eğil", "Ergani", "Hani", "Hazro", "Kayapınar", "Kocaköy", "Kulp", "Lice", "Silvan", "Sur", "Yenişehir" } };
            districtArray[21] = new District { cityCode = 22, cityName = "Edirne", districtName = new string[] { "Enez", "Havsa", "İpsala", "Keşan", "Lalapaşa", "Meriç", "Merkez", "Süloğlu", "Uzunköprü" } };
            districtArray[22] = new District { cityCode = 23, cityName = "Elazığ", districtName = new string[] { "Ağın", "Alacakaya", "Arıcak", "Baskil", "Elâzığ", "Karakoçan", "Keban", "Kovancılar", "Maden", "Palu", "Sivrice" } };
            districtArray[23] = new District { cityCode = 24, cityName = "Erzincan", districtName = new string[] { "Çayırlı", "Erzincan", "İliç", "Kemah", "Kemaliye", "Otlukbeli", "Refahiye", "Tercan", "Üzümlü" } };
            districtArray[24] = new District { cityCode = 25, cityName = "Erzurum", districtName = new string[] { "Aşkale", "Aziziye", "Çat", "Hınıs", "Horasan", "İspir", "Karaçoban", "Karayazı", "Köprüköy", "Narman", "Oltu", "Olur", "Palandöken", "Pasinler", "Pazaryolu", "Şenkaya", "Tekman", "Tortum", "Uzundere", "Yakutiye" } };
            districtArray[25] = new District { cityCode = 26, cityName = "Eskişehir", districtName = new string[] { "Alpu", "Beylikova", "Çifteler", "Günyüzü", "Han", "İnönü", "Mahmudiye", "Mihalgazi", "Mihalıççık", "Odunpazarı", "Sarıcakaya", "Seyitgazi", "Sivrihisar", "Tepebaşı" } };
            districtArray[26] = new District { cityCode = 27, cityName = "Gaziantep", districtName = new string[] { "Araban", "İslahiye", "Karkamış", "Nizip", "Nurdağı", "Oğuzeli", "Şahinbey", "Şehitkâmil", "Yavuzeli" } };
            districtArray[27] = new District { cityCode = 28, cityName = "Giresun", districtName = new string[] { "Alucra", "Bulancak", "Çamoluk", "Çanakçı", "Dereli", "Doğankent", "Espiye", "Eynesil", "Görele", "Güce", "Keşap", "Piraziz", "Şebinkarahisar", "Tirebolu", "Yağlıdere"} };
            districtArray[28] = new District { cityCode = 29, cityName = "Gümüşhane", districtName = new string[] { "Gümüşhane", "Kelkit", "Köse", "Kürtün", "Şiran", "Torul" } };
            districtArray[29] = new District { cityCode = 30, cityName = "Hakkâri", districtName = new string[] { "Çukurca", "Şemdinli", "Yüksekova" } };
            districtArray[30] = new District { cityCode = 31, cityName = "Hatay", districtName = new string[] { "Altınözü", "Antakya", "Arsuz", "Belen", "Defne", "Dörtyol", "Erzin", "Hassa", "İskenderun", "Kırıkhan", "Kumlu", "Payas", "Reyhanlı", "Samandağ", "Yayladağı" } };
            districtArray[31] = new District { cityCode = 32, cityName = "Isparta", districtName = new string[] { "Aksu", "Atabey", "Eğirdir", "Gelendost", "Gönen", "Keçiborlu", "Senirkent", "Sütçüler", "Şarkikaraağaç", "Uluborlu", "Yalvaç", "Yenişarbademli" } };
            districtArray[32] = new District { cityCode = 33, cityName = "Mersin", districtName = new string[] { "Akdeniz", "Anamur", "Aydıncık", "Bozyazı", "Çamlıyayla", "Erdemli", "Gülnar", "Mezitli", "Mut", "Silifke", "Tarsus", "Toroslar", "Yenişehir" } };
            districtArray[33] = new District { cityCode = 34, cityName = "İstanbul", districtName = new string[] { "Adalar", "Arnavutköy", "Ataşehir", "Avcılar", "Bağcılar", "Bahçelievler", "Bakırköy", "Başakşehir", "Bayrampaşa", "Beşiktaş", "Beykoz", "Beylikdüzü", "Beyoğlu", "Büyükçekmece", "Çatalca", "Çekmeköy", "Esenler", "Esenyurt", "Eyüp", "Fatih", "Gaziosmanpaşa", "Güngören", "Kadıköy", "Kağıthane", "Kartal", "Küçükçekmece", "Maltepe", "Pendik", "Sancaktepe", "Sarıyer", "Silivri", "Sultanbeyli", "Sultangazi", "Şile", "Şişli", "Tuzla", "Ümraniye", "Üsküdar", "Zeytinburnu" } };
            districtArray[34] = new District { cityCode = 35, cityName = "İzmir", districtName = new string[] { "Aliağa", "Balçova", "Bayındır", "Bayraklı", "Bergama", "Beydağ", "Bornova", "Buca", "Çeşme", "Çiğli", "Dikili", "Foça", "Gaziemir", "Güzelbahçe", "Karabağlar", "Karaburun", "Karşıyaka", "Kemalpaşa", "Kınık", "Kiraz", "Konak", "Menderes", "Menemen", "Narlıdere", "Ödemiş", "Seferihisar", "Selçuk", "Tire", "Torbalı", "Urla" } };
            districtArray[35] = new District { cityCode = 36, cityName = "Kars", districtName = new string[] { "Akyaka", "Arpaçay", "Digor", "Kağızman", "Sarıkamış", "Selim", "Susuz" } };
            districtArray[36] = new District { cityCode = 37, cityName = "Kastamonu", districtName = new string[] { "Abana", "Ağlı", "Araç", "Azdavay", "Bozkurt", "Cide", "Çatalzeytin", "Daday", "Devrekani", "Doğanyurt", "Hanönü", "İhsangazi", "İnebolu", "Küre", "Pınarbaşı", "Seydiler", "Şenpazar", "Taşköprü", "Tosya" } };
            districtArray[37] = new District { cityCode = 38, cityName = "Kayseri", districtName = new string[] { "Akkışla", "Bünyan", "Develi", "Felahiye", "Hacılar", "İncesu", "Kocasinan", "Melikgazi", "Özvatan", "Pınarbaşı", "Sarıoğlan", "Sarız", "Talas", "Tomarza", "Yahyalı", "Yeşilhisar" } };
            districtArray[38] = new District { cityCode = 39, cityName = "Kırklareli", districtName = new string[] { "Babaeski", "Demirköy", "Kırklareli", "Kofçaz", "Lüleburgaz", "Pehlivanköy", "Pınarhisar", "Vize" } };
            districtArray[39] = new District { cityCode = 40, cityName = "Kırşehir", districtName = new string[] { "Akçakent", "Akpınar", "Boztepe", "Çiçekdağı", "Kaman", "Mucur" } };
            districtArray[40] = new District { cityCode = 41, cityName = "Kocaeli", districtName = new string[] { "Başiskele", "Çayırova", "Darıca", "Derince", "Dilovası", "Gebze", "Gölcük", "İzmit", "Kandıra", "Karamürsel", "Kartepe", "Körfez" } };
            districtArray[41] = new District { cityCode = 42, cityName = "Konya", districtName = new string[] { "Ahırlı", "Akören", "Akşehir", "Altınekin", "Beyşehir", "Bozkır", "Cihanbeyli", "Çeltik", "Çumra", "Derbent", "Derebucak", "Doğanhisar", "Emirgazi", "Ereğli", "Güneysınır", "Hadım", "Halkapınar", "Hüyük", "Ilgın", "Kadınhanı", "Karapınar", "Karatay", "Kulu", "Meram", "Sarayönü", "Selçuklu", "Seydişehir", "Taşkent", "Tuzlukçu", "Yalıhüyük", "Yunak" } };
            districtArray[42] = new District { cityCode = 43, cityName = "Kütahya", districtName = new string[] { "Altıntaş", "Aslanapa", "Çavdarhisar", "Domaniç", "Dumlupınar", "Emet", "Gediz", "Hisarcık", "Pazarlar", "Şaphane", "Simav", "Tavşanlı" } };
            districtArray[43] = new District { cityCode = 44, cityName = "Malatya", districtName = new string[] { "Akçadağ", "Arapgir", "Arguvan", "Battalgazi", "Darende", "Doğanşehir", "Doğanyol", "Hekimhan", "Kale", "Kuluncak", "Pütürge", "Yazıhan", "Yeşilyurt" } };
            districtArray[44] = new District { cityCode = 45, cityName = "Manisa", districtName = new string[] { "Ahmetli", "Akhisar", "Alaşehir", "Demirci", "Gölmarmara", "Gördes", "Kırkağaç", "Köprübaşı", "Kula", "Salihli", "Sarıgöl", "Saruhanlı", "Selendi", "Soma", "Şehzadeler", "Turgutlu", "Yunusemre" } };
            districtArray[45] = new District { cityCode = 46, cityName = "Kahramanmaraş", districtName = new string[] { "Afşin", "Andırın", "Çağlayancerit", "Dulkadiroğlu", "Ekinözü", "Elbistan", "Göksun", "Nurhak", "Onikişubat", "Pazarcık", "Türkoğlu" } };
            districtArray[46] = new District { cityCode = 47, cityName = "Mardin", districtName = new string[] { "Artuklu", "Dargeçit", "Derik", "Kızıltepe", "Mazıdağı", "Midyat", "Nusaybin", "Ömerli", "Savur", "Yeşilli" } };
            districtArray[47] = new District { cityCode = 48, cityName = "Muğla", districtName = new string[] { "Bodrum", "Dalaman", "Datça", "Fethiye", "Kavaklıdere", "Köyceğiz", "Marmaris", "Menteşe", "Milas", "Ortaca", "Seydikemer", "Ula", "Yatağan" } };
            districtArray[48] = new District { cityCode = 49, cityName = "Muş", districtName = new string[] { "Bulanık", "Hasköy", "Korkut", "Malazgirt", "Varto" } };
            districtArray[49] = new District { cityCode = 50, cityName = "Nevşehir", districtName = new string[] { "Acıgöl", "Avanos", "Derinkuyu", "Gülşehir", "Hacıbektaş", "Kozaklı", "Ürgüp" } };
            districtArray[50] = new District { cityCode = 51, cityName = "Niğde", districtName = new string[] { "Altunhisar", "Bor", "Çamardı", "Çiftlik"   , "Ulukışla" } };
            districtArray[51] = new District { cityCode = 52, cityName = "Ordu", districtName = new string[] { "Akkuş", "Altınordu", "Aybastı", "Çamaş", "Çatalpınar", "Çaybaşı", "Fatsa", "Gölköy", "Gülyalı", "Gürgentepe", "İkizce", "Kabadüz", "Kabataş", "Korgan", "Kumru", "Mesudiye", "Perşembe", "Ulubey", "Ünye" } };
            districtArray[52] = new District { cityCode = 53, cityName = "Rize", districtName = new string[] { "Ardeşen", "Çamlıhemşin", "Çayeli", "Derepazarı", "Fındıklı", "Güneysu", "Hemşin", "İkizdere", "İyidere", "Kalkandere", "Pazar" } };
            districtArray[53] = new District { cityCode = 54, cityName = "Sakarya", districtName = new string[] { "Adapazarı", "Akyazı", "Arifiye", "Erenler", "Ferizli", "Geyve", "Hendek", "Karapürçek", "Karasu", "Kaynarca", "Kocaali", "Pamukova", "Sapanca", "Serdivan", "Söğütlü", "Taraklı" } };
            districtArray[54] = new District { cityCode = 55, cityName = "Samsun", districtName = new string[] { "Alaçam", "Asarcık", "Atakum", "Ayvacık", "Bafra", "Canik", "Çarşamba", "Havza", "İlkadım", "Kavak", "Ladik", "Ondokuzmayıs", "Salıpazarı", "Tekkeköy", "Terme", "Vezirköprü", "Yakakent" } };
            districtArray[55] = new District { cityCode = 56, cityName = "Siirt", districtName = new string[] { "Tillo", "Baykan", "Eruh", "Kurtalan", "Pervari", "Şirvan" } };
            districtArray[56] = new District { cityCode = 57, cityName = "Sinop", districtName = new string[] { "Ayancık", "Boyabat", "Dikmen", "Durağan", "Erfelek", "Gerze", "Saraydüzü", "Türkeli" } };
            districtArray[57] = new District { cityCode = 58, cityName = "Sivas", districtName = new string[] { "Akıncılar", "Altınyayla", "Divriği", "Doğanşar", "Gemerek", "Gölova", "Hafik", "İmranlı", "Kangal", "Koyulhisar", "Suşehri", "Şarkışla", "Ulaş", "Yıldızeli", "Zara", "Gürün" } };
            districtArray[58] = new District { cityCode = 59, cityName = "Tekirdağ", districtName = new string[] { "Çerkezköy", "Çorlu", "Ergene", "Hayrabolu", "Kapaklı", "Malkara", "Marmara Ereğlisi", "Muratlı", "Saray", "Süleymanpaşa", "Şarköy" } };
            districtArray[59] = new District { cityCode = 60, cityName = "Tokat", districtName = new string[] { "Almus", "Artova", "Başçiftlik", "Erbaa", "Niksar", "Pazar", "Reşadiye", "Sulusaray", "Turhal", "Yeşilyurt", "Zile" } };
            districtArray[60] = new District { cityCode = 61, cityName = "Trabzon", districtName = new string[] { "Akçaabat", "Araklı", "Arsin", "Beşikdüzü", "Çarşıbaşı", "Çaykara", "Dernekpazarı", "Düzköy", "Hayrat", "Köprübaşı", "Maçka", "Of", "Ortahisar", "Sürmene", "Şalpazarı", "Tonya", "Vakfıkebir", "Yomra" } };
            districtArray[61] = new District { cityCode = 62, cityName = "Tunceli", districtName = new string[] { "Çemişgezek", "Hozat", "Mazgirt", "Nazımiye", "Ovacık", "Pertek", "Pülümür", "Tunceli" } };
            districtArray[62] = new District { cityCode = 63, cityName = "Şanlıurfa", districtName = new string[] { "Akçakale", "Birecik", "Bozova", "Ceylanpınar", "Eyyübiye", "Halfeti", "Haliliye", "Harran", "Hilvan", "Karaköprü", "Siverek", "Suruç", "Viranşehir" } };
            districtArray[63] = new District { cityCode = 64, cityName = "Uşak", districtName = new string[] { "Banaz", "Eşme", "Karahallı", "Sivaslı", "Ulubey" } };
            districtArray[64] = new District { cityCode = 65, cityName = "Van", districtName = new string[] { "Bahçesaray", "Başkale", "Çaldıran", "Çatak", "Edremit", "Erciş", "Gevaş", "Gürpınar", "İpekyolu", "Muradiye", "Özalp", "Saray", "Tuşba" } };
            districtArray[65] = new District { cityCode = 66, cityName = "Yozgat", districtName = new string[] { "Akdağmadeni", "Aydıncık", "Boğazlıyan", "Çandır", "Çayıralan", "Çekerek", "Kadışehri", "Saraykent", "Sarıkaya", "Sorgun", "Şefaatli", "Yenifakılı", "Yerköy" } };
            districtArray[66] = new District { cityCode = 67, cityName = "Zonguldak", districtName = new string[] { "Alaplı", "Çaycuma", "Devrek", "Gökçebey", "Kilimli", "Kozlu", "Karadeniz Ereğli" } };
            districtArray[67] = new District { cityCode = 68, cityName = "Aksaray", districtName = new string[] { "Ağaçören", "Eskil", "Gülağaç", "Güzelyurt", "Ortaköy", "Sarıyahşi" } };
            districtArray[68] = new District { cityCode = 69, cityName = "Bayburt", districtName = new string[] { "Aydıntepe", "Bayburt (İl merkezi)", "Demirözü" } };
            districtArray[69] = new District { cityCode = 70, cityName = "Karaman", districtName = new string[] { "Ayrancı", "Başyayla", "Ermenek", "Kazımkarabekir", "Sarıveliler" } };
            districtArray[70] = new District { cityCode = 71, cityName = "Kırıkkale", districtName = new string[] { "Bahşılı", "Balışeyh", "Çelebi", "Delice", "Karakeçili", "Keskin", "Sulakyurt", "Yahşihan" } };
            districtArray[71] = new District { cityCode = 72, cityName = "Batman", districtName = new string[] { "Beşiri", "Gercüş", "Hasankeyf", "Kozluk", "Sason" } };
            districtArray[72] = new District { cityCode = 73, cityName = "Şırnak", districtName = new string[] { "Beytüşşebap", "Cizre", "Güçlükonak", "İdil", "Silopi", "Uludere" } };
            districtArray[73] = new District { cityCode = 74, cityName = "Bartın", districtName = new string[] { "Amasra", "Kurucaşile", "Ulus" } };
            districtArray[74] = new District { cityCode = 75, cityName = "Ardahan", districtName = new string[] { "Çıldır", "Damal", "Göle", "Hanak", "Posof" } };
            districtArray[75] = new District { cityCode = 76, cityName = "Iğdır", districtName = new string[] { "Aralık", "Karakoyunlu", "Tuzluca" } };
            districtArray[76] = new District { cityCode = 77, cityName = "Yalova", districtName = new string[] { "Altınova", "Armutlu", "Çınarcık", "Çiftlikköy", "Termal" } };
            districtArray[77] = new District { cityCode = 78, cityName = "Karabük", districtName = new string[] { "Eflani", "Eskipazar", "Ovacık", "Safranbolu", "Yenice" } };
            districtArray[78] = new District { cityCode = 79, cityName = "Kilis", districtName = new string[] { "Elbeyli", "Musabeyli", "Polateli" } };
            districtArray[79] = new District { cityCode = 80, cityName = "Osmaniye", districtName = new string[] { "Bahçe", "Düziçi", "Hasanbeyli", "Kadirli", "Sumbas", "Toprakkale" } };
            districtArray[80] = new District { cityCode = 81, cityName = "Düzce", districtName = new string[] { "Akçakoca", "Cumayeri", "Çilimli", "Gölyaka", "Gümüşova", "Kaynaşlı", "Yığılca" } };

        }

    }
}
